export enum ErrorCodes {
  INVALID_INPUT = "INVALID_INPUT",
  UNAUTHORIZED = "UNAUTHORIZED",
  NOT_FOUND = "NOT_FOUND",
  INTERNAL_ERROR = "INTERNAL_ERROR",
  PLAY_CARD_ACTION_FAILED = "PLAY_CARD_ACTION_FAILED",
  UNSUPPORTED_ACTION = "UNSUPPORTED_ACTION",
  GAME_START_FAILED = "GAME_START_FAILED",
}
